version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pokerangers-network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5001:8080"
    volumes:
      - pokemon_data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - pokerangers-network

networks:
  pokerangers-network:
    driver: bridge

volumes:
  pokemon_data: